Kmcgill autofill
triton-inference-server/tensorflow_backend pull request #50
Opened 2022-03-22 19:54 UTC by nv-kmcgill53

If the model config can be autofilled and the model supports batching, we now default to a max_batch_size of 4 instead of 1.

2022-03-22 20:39 UTC, tanmayv25 commented
@nv-kmcgill53  You can add reviews from the top right of the page. That way we would get notification that you have got a PR and it is ready for review.

2022-03-22 20:43 UTC, tanmayv25 requested changes

2022-03-22 20:43 UTC, tanmayv25 commented on src/tensorflow.cc
> -    const int new_max_batch_size = model_support_batching_ ? 1 : 0;
Update the comment in L1284 to reflect the changes.

2022-03-22 20:49 UTC, tanmayv25 commented
Note: Just changing the max_batch_size to 4 would not have any affect on the performance seen by the user. Just that the server will not reject the requests that have batch size of 2,3 or 4.  
In order to actually make some improvement, you should enable "dynamic_batching" in the model config. I have question around how the magic number 4 was selected. Does it generally work well with the most of the typical models?
Wouldn't it make more sense to add a `--default-max-batch-size` option in tritonserver cli and use that to populate these values in auto-complete?

2022-03-22 22:18 UTC, nv-kmcgill53 commented
Thanks for reminding me about enabling the "dynamic_batching" in the model config. As for the magic number 4, I went off the advice of @deadeyegoodwin as he thought defaulting the value to 4 was ok for those models which support batching. I am not opposed to investigating this more before asserting this value as a good choice.

As for the design which you suggested, I agree with you that allowing it to be a command line option rather than a hard coded value is superior. I will work on this change.

2022-03-22 22:22 UTC, deadeyegoodwin commented
I think making the default auto-complete max batch size a backend_config parameter may be the better way to go. --backend-config is meant to be the generic way to pass any configuration information to the backends.

2022-03-23 06:51 UTC, CoderHam requested changes
I agree that we should expose the default max_batch_size as a parameter for the user to control via --backend-config but I would rather we make it a global parameter for all backends rather than specific to a backend. 

That being said we could allow a new mode of passing --backend-config="default-max-batch-size=<>"

Notice how no backend is specified. In such a case it would add that config setting for all the backends.

2022-03-23 06:51 UTC, CoderHam commented on src/tensorflow.cc
>             "in model configuration. Must specify max_batch_size to utilize "
Must specify max_batch_size manually to use a different max batch size than the default.

2022-03-23 06:51 UTC, CoderHam commented on src/tensorflow.cc
> +          (std::string("autofilled max_batch_size to 4 for model '") +
autofilled max_batch_size to a default value of 4 for model

2022-03-23 18:17 UTC, nv-kmcgill53 commented
For the user who has multiple backends and whose models in each of the backends can support dynamic batching, what you are suggesting is that we allow setting a global value for the default-max-batch-size rather than to specific backend. The user, with the proposed change, only has to define the value once rather than per backend on the command line.

The use case of this feature as I understand it is for the user who has not utilized the model analyzer, who wants to set a reasonable max batch size by default. Anything more nuanced, we would suggest the user use the model analyzer to generate the optimal model configuration. Is this correct?  If so, I am swayed more towards the global configuration rather than the per-backend configuration. 

How likely is it that a user wants to set two (multiple) different 'default-max-batch-size's, one for each backend? If the answer is small to none then making this a --backend-config would be moot, and it would be up to the backend to implement this global default value. Thoughts?

2022-03-23 19:07 UTC, tanmayv25 commented
> what you are suggesting is that we allow setting a global value for the default-max-batch-size rather than to specific backend. The user, with the proposed change, only has to define the value once rather than per backend on the command line.

Yes. That's the benefit of specifying it just once. `--backend-config="default_max_batch_size=<>"`
So, for any backends working on batching models, that can not detect max_batch_size by themselves will use this value when auto-completing their respective configs. 

> The use case of this feature as I understand it is for the user who has not utilized the model analyzer, who wants to set a reasonable max batch size by default. Anything more nuanced, we would suggest the user use the model analyzer to generate the optimal model configuration. Is this correct? If so, I am swayed more towards the global configuration rather than the per-backend configuration.

That is correct. I am also in favor of a global --backend-config="default_max_batch_size=<>". If it is not supplied by the user, the default value of "default_max_batch_size" can be 4.

> How likely is it that a user wants to set two (multiple) different 'default-max-batch-size's, one for each backend?

It is not likely and I believe allowing that would be a classic case of over-engineering. So instead of `--backend-config tensorflow,default_max_batch_size=4`, we are proposing `--backend-config default_max_batch_size=4`.

2022-03-23 20:13 UTC, deadeyegoodwin commented
Specifying --backend-config=tensorflow,default_max_batch_size=4 will still be allowed so really we are able to support both cases.

2022-05-03 16:58 UTC, nv-kmcgill53 commented
The discussion had in this PR is correct but the code submitted is not. Closing this PR as obsolete.

2022-05-03 16:58 UTC, closed without merging